<?php
//Header file
session_start();
ob_start();
print "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">";
print "<html xmlns=\"http://www.w3.org/1999/xhtml\">";
print "<head>";
print "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />";
print "<title>";
$PageTitle;
print "</title>";
print "<link href=\"./template/main.css\" rel=\"stylesheet\" type=\"text/css\" />";
print "</head>";
print "";
print "<body>";
print "<div id=\"topheader\" align=\"center\">";
print "<table bgcolor=\"#FFFFFF\" width=\"950\">";
print "<tr><td>";
print " <table width=\"100%\">";
print "  <tr>";
print "   <td>";
print "    <div id=\"boxshadow\">";
print "     <img src=\"./template/images/sharing-tree-logo.jpg\" width=\"950\" />";
print "    </div>";
print "   </td>";
print "  </tr>";
print "  <!--";
print "  <tr>";
print "    <td width=\"100%\">";
print "      <div id=\"menu\">";
print "       <ul>";
print "        <li><a href=\"index.php\">HOME</a></li>";
print "       </ul>";
print "      </div>";
print "    </td>";
print "  </tr>";
print "  -->";
print " </table>";
print "</td></tr>";
print "<tr><td>";
?>
